# -*- coding = utf-8 -*-

# Select GPU
gpu = "cuda:0"

# Fix random seed for reproducibility
random_seed = 42

[data]
path_test = "data/dta-reviEvalCorpus-v1/dtaec-test.jsonl"

[tokenizer]
checkpoint_in = "google/byt5-small"

[tokenizer_configs]
padding = "longest" # pad to the longest sequence in batch
truncation = false

[model]
checkpoint = "ybracke/transnormer-19c-beta-v02"

[generation]
batch_size = 32

[generation_config]
# See here for more options: https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig
max_new_tokens = 2048
early_stopping = false
length_penalty = 2.0 # length_penalty > 0.0 promotes longer sequences
num_beams = 4
